### ISSUE TITLE
Parallel Color Issue

### ISSUE THREAD

**Issue by jordanadania** [zombodotcom/AuraRadiate2#2]
`FastLED.addLeds<WS2812B, 23, GRB>(leds, NUM_LEDS);`

`FastLED.addLeds<WS2811, 32, RGB>(leds, NUM_LEDS);`

With that code, the WS2812B strip runs correctly, but the WS2811 code swaps the Red and Green. Switching the WS2811 to GRB has no effect.

Putting the WS2811 line before the WS2812B gives opposite results. The WS2811 strip will run correctly, but the WS2812B strip would have Red and Green swapped. Switching the WS2812B to RGB has no effect.

**Comment by zombodotcom** [comment]
this code is kind of old. 

and I have never tried using 2 different kinds of strips. it should work, but I can't really test it because my ws2811's are back at home and I'm on vacation. i did bring ws2812b's though lol

**Comment by jordanadania** [comment]
https://github.com/FastLED/FastLED/issues/827#issuecomment-505668673

**Comment by jordanadania** [comment]
samguyer updated FastLED. this is no longer an issue
